export const Strings = {
  appName: 'RNStarterKit',
  apiErrorTitle: 'Opps!',
  apiErrorDesc: 'Something went wrong',
  noInternetTitle: 'No Connctivity!',
  noInternetDesc: 'Seems your internet is down',
  refresh: 'Refresh',
  ok: 'OK',
  cancel: 'Cancel',
  skip: 'Skip',
  back: 'Back',
  createAnAccount: 'Create an \naccount',
  registerMobile: 'Register with your ',
  byClickingThe: 'By clicking the ',
  youAgreeToOurTerms: ' button, you agree to our Terms & Conditions',
  loginMobile: 'Login with your registered ',
  login: 'Login',
  forgotPassword: 'Forgot Password',
  loginEmail: 'Login with Email',
  mobileNumber: 'Mobile Number',
  mobileNo: 'Mobile No',
  title: 'Title',
  posted: 'Posted',
  userNameOrEmail: 'Username or Email',
  name: 'Name',
  userName: 'Username',
  emailID: 'Email ID',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  registerButton: 'Register',
  registerEmail: 'Register with Email',
  todayForJoe: 'Today for',
  explore: 'Explore',
  shows: 'Shows',
  gerne: 'Genre',
  shorts: 'Shorts',
  register: 'Register',
  or: 'Or',
  jobsHub: '’s Hub',
  gigs: 'Gigs',
  courses: 'Courses',
  welcomeBack: 'Welcome \nBack',
  phoneVerification: 'Phone \nVerification',
  pleaseEnter: 'Please enter the 6 digit code sent you at',
  resendCode: 'Resend Code',
  notification: 'Notifications',
  noData: 'No Data Available',
  noVideo: 'No Videos Yet',
  more: 'more...',
  followShow: 'Follow Show',
  followingShow: 'Following Show',
  showCreators: 'Show Creators',
  showDesc: 'Creators featured in the making of this series',
  follow: 'Follow',
  following: 'Following',
  uploadVideo: 'Upload Video',
  submitPitch: 'Submit Pitch',
  react: 'React',
  episodes: 'Episodes',
  reactions: 'Reactions',
  logout: 'Logout',
  stock: 'Stock',
  story: 'Story',
  videoTitle: 'Video Title',
  location: 'Location',
  videoDesc: 'Video Description',
  submitFootage: 'Submit Footage',
  aboutMe: 'About Me',
  loadMore: 'Load More',
  apply: 'Apply',
  bookNow: 'Book Now',
  publishedOn:'Published on'
};
